name: Create Prerelease

on: workflow_dispatch

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        name: Create release PR
        with:
          release-type: node
          package-name: 'micropub-helper'
          prerelease: true
          default-branch: next

      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-node@v3
        name: Setup node
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        name: Install dependencies

      - run: npm test
        name: Run tests

      - run: npm run build
        name: Run build

      - run: npm publish --tag next
        name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
