name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        name: Create release PR
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v3
        name: Checkout code
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v3
        name: Setup node
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}

      - run: npm test
        name: Run tests
        if: ${{ steps.release.outputs.release_created }}

      - run: npm run build
        name: Run build
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish --provenance --access public
        name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
